# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Flamelily Retro
description: >- # this means to ignore newlines until "baseurl:"
  All your retro SCSI and PCB needs in one place. New stuff for old tech.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://shop.flamelily.co.uk" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: FlamelilyIT
github_username:  flamelily-bluescsi
lang: en

# Build settings
# theme: tactile
remote_theme: pages-themes/tactile
plugins:
  - jekyll-feed
  - jekyll-remote-theme

icon: "&#128722;"
# Stock
db25: 14
desktop: 16
powerbook: 9
pico2: 3
pico2w: 3
picogus: 8
picomem: 14
adlib: 6
denise: 0
alicia: 0
nic: 3
cffloppy: 9
powershark: 0
vgaadapter: 10
cpu: 10
dac: 9
rtc: 10
juicebox: 0
scsiadapter: 6
framethrower: 5
ram: 6
t2adapter: 0
ultranarrow50: 1
ultrawide68: 1
ultrawide80: 0
narrowexpander: 1
audionarrowwide: 1

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
